// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function BuildTime() {
  return window['go']['main']['App']['BuildTime']();
}

export function Quiz(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['Quiz'](arg1, arg2, arg3, arg4);
}
